services:
  frontend:
    build:
      context: ./crud-from/
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./CRUD-SpringBoot-Backaend/demo/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XE
      - SPRING_DATASOURCE_USERNAME=jesus
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.OracleDialect
    depends_on:
      - oracle-db
    networks:
      - app-network

  oracle-db:
    image: gvenzl/oracle-xe:11
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=123
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  oracle-data:
