services:
  frontend:
    build:
      context: ./crud-from/
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:5173:80
    depends_on:
      - backend

  backend:
    build:
      context: ./CRUD-SpringBoot-Backaend/demo/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/XE
      - SPRING_DATASOURCE_USERNAME=jesus
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - oracle-db

  oracle-db:
    image: gvenzl/oracle-xe:11
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=123
      - ORACLE_DATABASE=XE
      - ORACLE_USERNAME=jesus
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-L",
          "jesus/123@//localhost:1521/XE",
          "AS",
          "SYSDBA",
          "SELECT",
          "1",
          "FROM",
          "DUAL",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
