services:
  db:
    image: gvenzl/oracle-xe:11
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=123
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "/ as sysdba", "exit"]
      interval: 30s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./CRUD-SpringBoot-Backaend/demo
      dockerfile: Dockerfile
    container_name: spring-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XE
      - SPRING_DATASOURCE_USERNAME=jesus
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: ./crud-from
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  oracle-data:
